var stateData = {
  qb: {
    name: "Quarterback",
    averageHeight: "6'2\" to 6'5\"",
    averageWeight: "215 to 240 lbs",
    goat: "Tom Brady",
    whatTheyDo:
      "Lead the offense, throw passes, hand off the ball, read defenses and call plays.",
    positionType: "Offense",
    notes: "Primary leader of the offense and main passer in most formations.",
    image: "../QB.jpg",
    goatImage: "../QbGoat.jpg",
  },
  rb: {
    name: "Running Back",
    averageHeight: "5'10\" to 6'1\"",
    averageWeight: "205 to 230 lbs",
    goat: "Barry Sanders",
    whatTheyDo:
      "Run the ball, catch passes out of the backfield, block for the quarterback.",
    positionType: "Offense",
    notes: "Versatile offensive weapon used in rushing and passing plays.",
    image: "../RB.jpg",
    goatImage: "../RbGoat.jpg",
  },
  wr: {
    name: "Wide Receiver",
    averageHeight: "5'11\" to 6'4\"",
    averageWeight: "190 to 220 lbs",
    goat: "Jerry Rice",
    whatTheyDo: "Run routes, catch passes, create separation from defenders.",
    positionType: "Offense",
    notes: "Primary pass catcher and deep threat in the passing game.",
    image: "../WR.jpg",
    goatImage: "../WrGoat.jpg",
  },
  oline: {
    name: "O-Line",
    averageHeight: "6'3\" to 6'7\"",
    averageWeight: "300 to 330 lbs",
    goat: "Larry Allen",
    whatTheyDo: "Protect the quarterback, block for runners, and open lanes.",
    positionType: "Offense",
    notes:
      "Includes tackles, guards and center; the foundation of the offense.",
    image: "../O line.jpg",
    goatImage: "../OlineGoat.jpg",
  },
  dline: {
    name: "D-Line",
    averageHeight: "6'2\" to 6'7\"",
    averageWeight: "280 to 320 lbs",
    goat: "Arron Donald",
    whatTheyDo: "Rush the passer, stop the run, and control the line.",
    positionType: "Defense",
    notes:
      "Includes defensive ends and tackles; first defenders in the trenches.",
    image: "../D line.jpg",
    goatImage: "../DlineGoat.jpg",
  },
  